export default [
  ' Hakkında',
  'Yardım Merkezi',
  'Hizmet Şartları',
  'Gizlilik Politikası',
  'Çerez Politikası',
  'Iletisim bilgileri',
  'Reklam bilgisi',
  'Blog',
  'Durum',
  'Kariyer',
  'Marka Kaynakları',
  'Reklam',
  'Pazarlama',
  'İşletmeler İçin Twitter',
  'Geliştiriciler',
  'Dizin',
  'Ayarlar',
  '© 2021 Twitter, Inc.',
];
